"""added persons

Revision ID: 2416e73489fa
Revises: 533c2f96b79e
Create Date: 2026-02-17 08:19:28.937420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2416e73489fa'
down_revision = '533c2f96b79e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('persons', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('radar', sa.Boolean(), nullable=False))
        batch_op.drop_column('motion')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motion', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.drop_column('radar')
        batch_op.drop_column('persons')

    # ### end Alembic commands ###
