"""initial

Revision ID: 533c2f96b79e
Revises: 
Create Date: 2026-02-11 09:51:47.213576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533c2f96b79e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('humidity', sa.Float(), nullable=False),
    sa.Column('voc', sa.Float(), nullable=False),
    sa.Column('motion', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    # ### end Alembic commands ###
